https://www.youtube.com/watch?v=3G3zExNItj0&t=303&ab_channel=%EC%A1%B0%EC%BD%94%EB%94%A9JoCoding

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
plt.rc('font', family='Malgun Gothic')
import matplotlib as mpl
mpl.rcParams['axes.unicode_minus'] = False
import seaborn as sns
import tqdm

from sklearn.preprocessing import OneHotEncoder

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler


from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier            # Voting 기법 사용 Module
from sklearn.neighbors import KNeighborsClassifier 
import xgboost as xgb
import lightgbm as lgb

import warnings
warnings.filterwarnings('ignore')

Data Load

In [12]:
df = pd.read_csv('./data/lotto.csv', index_col=0)
df

ValueError: could not convert string 'num,1,2,3,4,5,6,bonus,1st,2nd,3rd,4th,5th' to float64 at row 0, column 1.

In [4]:
df.index

Int64Index([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
            ...
            1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086],
           dtype='int64', name='num', length=1086)

In [5]:
df.columns

Index(['1', '2', '3', '4', '5', '6', 'bonus', '1st', '2nd', '3rd', '4th',
       '5th'],
      dtype='object')

One Hot Encoding

In [6]:
# one-hot encoding

# 당첨번호를 원핫인코딩벡터(ohbin)으로 변환
def numbers2ohbin(numbers):

    ohbin = np.zeros(45) #45개의 빈 칸을 만듬

    for i in range(6): #여섯개의 당첨번호에 대해서 반복함
        ohbin[int(numbers[i])-1] = 1 #로또번호가 1부터 시작하지만 벡터의 인덱스 시작은 0부터 시작하므로 1을 뺌
    
    return ohbin

# 원핫인코딩벡터(ohbin)를 번호로 변환
def ohbin2numbers(ohbin):

    numbers = []
    
    for i in range(len(ohbin)):
        if ohbin[i] == 1.0: # 1.0으로 설정되어 있으면 해당 번호를 반환값에 추가한다.
            numbers.append(i+1)
    
    return numbers
     

In [24]:
rows = df.values
row_count = len(rows)

numbers = rows[:, 1:7]
lotto_onehot = list(map(numbers2ohbin, numbers))

x_samples = lotto_onehot[0:row_count-1]
y_samples = lotto_onehot[1:row_count]

#원핫인코딩으로 표시
print("lotto_onehot")
print("X[0]: " + str(x_samples[0]))
print("Y[0]: " + str(y_samples[0]))

#번호로 표시
print("numbers")
print("X[0]: " + str(ohbin2numbers(x_samples[0])))
print("Y[0]: " + str(ohbin2numbers(y_samples[0])))

lotto_onehot
X[0]: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
Y[0]: [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
numbers
X[0]: [16, 23, 29, 33, 37, 40]
Y[0]: [2, 13, 21, 25, 32, 42]


In [29]:
lotto_onehot

[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 

In [39]:
lotto_df = pd.DataFrame(lotto_onehot, columns=np.arange(1,46), index = np.arange(1, 1087))
lotto_df = lotto_df.astype(int)
lotto_df

1   2   3   4   5   6   7   8   9   10  ...  36  37  38  39  40  41  42  \
1      0   0   0   0   0   0   0   0   0   0  ...   0   1   0   0   1   0   0   
2      0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   
3      0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4      0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   1   0   1   
5      0   0   1   0   0   0   0   0   0   0  ...   0   0   0   0   1   1   1   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
1082   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   1   
1083   0   0   0   0   0   0   1   0   0   0  ...   0   0   1   0   0   0   0   
1084   0   0   0   0   1   0   0   0   0   0  ...   0   0   0   0   0   0   1   
1085   0   0   0   0   0   0   1   0   0   0  ...   1   0   1   0   0   0   0   
1086   0   0   0   0   0   0   0   0   0   0  ...   1   1   0   0   0   0   0   

      43  44  45  
1      0   0   0  
2      0   0   0  
3      0   0   0  
4      0   0   0  
5      0   0   0  
...   ..  ..  ..  
1082   0   0   0  
1083   0   0   0  
1084   0   0   0  
1085   0   1   0  
1086   0   0   0  

[1086 rows x 45 columns]

Modeling

In [41]:
# train test spilt 

X = lotto_df.index
y = lotto_df.values

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=777)

print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)

(868,) (868, 45)
(218,) (218, 45)


In [46]:
y[0]

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [49]:
# Model Load
dt = DecisionTreeClassifier()
# rf = RandomForestClassifier()
# xgb = xgb.XGBClassifier()
# lgb = lgb.LGBMClassifier()

# Training 
dt.fit(X_train, y_train[0].reshape(-1, 1))
# rf.fit(X_train, y_train)
# xgb.fit(X_train, y_train)
# lgb.fit(X_train, y_train)

# Predict 
dt_pred = dt.predict(X_val)
# rf_pred = rf.predict(X_val)
# xgb_pred = xgb.predict(X_val)
# lgb_pred = lgb.predict(X_val)

ValueError: Expected 2D array, got 1D array instead:
array=[5.500e+01 7.510e+02 8.300e+01 9.800e+01 4.870e+02 5.920e+02 7.900e+01
 9.270e+02 4.330e+02 6.300e+02 7.760e+02 1.980e+02 4.000e+01 6.160e+02
 7.600e+01 1.480e+02 1.600e+01 4.610e+02 1.020e+03 8.860e+02 8.020e+02
 1.940e+02 7.970e+02 1.120e+02 8.900e+02 1.520e+02 5.380e+02 1.790e+02
 5.680e+02 4.150e+02 7.220e+02 1.930e+02 6.060e+02 7.730e+02 4.350e+02
 7.630e+02 9.810e+02 9.940e+02 1.083e+03 5.400e+01 9.740e+02 2.370e+02
 3.210e+02 1.330e+02 7.500e+02 1.000e+01 6.900e+01 5.900e+02 6.630e+02
 5.600e+02 2.980e+02 4.950e+02 6.450e+02 1.200e+02 2.900e+02 2.560e+02
 1.008e+03 8.140e+02 5.130e+02 2.810e+02 7.820e+02 1.130e+02 9.460e+02
 2.540e+02 1.920e+02 5.320e+02 1.020e+02 4.740e+02 2.180e+02 2.700e+02
 6.660e+02 3.870e+02 5.910e+02 1.750e+02 8.040e+02 8.450e+02 9.310e+02
 3.160e+02 5.500e+02 4.770e+02 2.250e+02 2.070e+02 9.950e+02 8.750e+02
 4.980e+02 3.600e+01 6.480e+02 1.710e+02 8.270e+02 1.470e+02 3.810e+02
 1.860e+02 8.310e+02 8.500e+02 3.900e+01 9.890e+02 2.050e+02 6.470e+02
 6.710e+02 1.070e+02 5.520e+02 7.740e+02 4.040e+02 3.020e+02 3.070e+02
 2.400e+02 4.840e+02 7.840e+02 4.700e+02 4.660e+02 4.200e+02 3.190e+02
 2.690e+02 2.470e+02 1.046e+03 2.880e+02 7.290e+02 8.810e+02 3.060e+02
 9.570e+02 9.410e+02 1.640e+02 6.000e+01 5.100e+01 7.880e+02 2.830e+02
 3.110e+02 5.080e+02 2.720e+02 1.007e+03 6.830e+02 3.450e+02 9.150e+02
 6.410e+02 6.100e+02 1.043e+03 3.090e+02 1.670e+02 4.800e+02 8.470e+02
 4.780e+02 1.780e+02 4.230e+02 9.800e+02 7.110e+02 1.059e+03 6.590e+02
 9.280e+02 6.810e+02 9.580e+02 4.160e+02 8.130e+02 9.780e+02 7.350e+02
 6.140e+02 7.660e+02 9.700e+02 4.550e+02 7.120e+02 8.290e+02 2.620e+02
 5.820e+02 8.700e+01 1.770e+02 8.620e+02 2.760e+02 2.780e+02 9.710e+02
 4.390e+02 4.070e+02 1.430e+02 8.390e+02 7.030e+02 9.600e+01 2.110e+02
 8.350e+02 1.800e+01 7.980e+02 6.420e+02 7.860e+02 5.200e+02 7.440e+02
 1.011e+03 7.400e+02 1.220e+02 1.490e+02 9.700e+01 9.900e+01 9.260e+02
 5.860e+02 1.160e+02 1.340e+02 5.570e+02 3.480e+02 1.080e+02 6.230e+02
 3.910e+02 1.450e+02 2.800e+02 1.380e+02 5.430e+02 3.500e+01 4.300e+02
 4.970e+02 6.740e+02 9.300e+02 4.290e+02 5.700e+02 8.990e+02 7.520e+02
 4.260e+02 9.690e+02 3.040e+02 7.680e+02 8.800e+01 5.090e+02 9.100e+01
 2.500e+02 8.540e+02 2.150e+02 3.610e+02 5.800e+01 3.170e+02 6.730e+02
 8.780e+02 1.620e+02 2.230e+02 3.030e+02 6.200e+01 7.460e+02 2.100e+02
 1.580e+02 2.680e+02 1.071e+03 2.910e+02 9.300e+01 2.940e+02 2.300e+01
 7.330e+02 5.240e+02 8.800e+02 2.740e+02 9.330e+02 5.260e+02 1.950e+02
 7.310e+02 3.920e+02 9.770e+02 5.000e+00 7.340e+02 2.920e+02 6.510e+02
 6.030e+02 3.460e+02 3.010e+02 6.640e+02 2.160e+02 2.350e+02 4.680e+02
 1.300e+02 7.700e+02 1.036e+03 8.120e+02 7.580e+02 3.540e+02 3.580e+02
 7.810e+02 4.860e+02 8.710e+02 5.900e+01 4.710e+02 8.850e+02 8.730e+02
 4.890e+02 1.000e+03 8.900e+01 2.790e+02 2.500e+01 9.090e+02 5.490e+02
 4.700e+01 2.750e+02 6.210e+02 1.031e+03 4.800e+01 6.180e+02 1.310e+02
 2.460e+02 7.570e+02 1.028e+03 9.520e+02 6.580e+02 5.470e+02 1.068e+03
 4.820e+02 7.780e+02 2.600e+01 5.690e+02 5.590e+02 7.130e+02 1.052e+03
 7.470e+02 6.330e+02 8.790e+02 6.920e+02 2.850e+02 4.900e+02 6.600e+01
 3.270e+02 6.400e+01 3.470e+02 6.020e+02 9.910e+02 5.000e+02 9.000e+01
 2.820e+02 9.120e+02 9.240e+02 6.620e+02 1.050e+03 5.880e+02 5.370e+02
 4.580e+02 3.180e+02 1.500e+01 3.390e+02 6.600e+02 5.290e+02 6.300e+01
 1.010e+03 3.000e+01 9.080e+02 9.030e+02 2.870e+02 9.600e+02 3.320e+02
 1.810e+02 3.590e+02 3.600e+02 8.000e+02 3.050e+02 4.930e+02 7.940e+02
 8.320e+02 1.035e+03 6.040e+02 2.290e+02 1.004e+03 7.790e+02 7.300e+01
 9.560e+02 3.950e+02 5.070e+02 3.730e+02 8.830e+02 1.900e+01 5.650e+02
 1.025e+03 6.700e+01 4.460e+02 3.650e+02 1.880e+02 4.440e+02 8.740e+02
 1.110e+02 7.800e+01 4.880e+02 4.310e+02 9.750e+02 1.084e+03 2.840e+02
 9.490e+02 9.160e+02 3.900e+02 5.000e+01 4.600e+01 4.990e+02 8.220e+02
 6.670e+02 8.520e+02 1.630e+02 9.870e+02 3.700e+02 1.016e+03 3.360e+02
 1.260e+02 7.490e+02 3.790e+02 2.440e+02 8.550e+02 1.230e+02 9.960e+02
 9.930e+02 7.960e+02 1.560e+02 1.064e+03 1.063e+03 2.320e+02 7.560e+02
 7.590e+02 2.510e+02 7.230e+02 3.080e+02 1.029e+03 2.060e+02 1.049e+03
 6.860e+02 2.120e+02 7.950e+02 6.360e+02 1.660e+02 9.400e+02 4.220e+02
 7.190e+02 1.022e+03 2.300e+02 4.750e+02 6.910e+02 8.660e+02 5.740e+02
 1.240e+02 1.680e+02 5.420e+02 9.370e+02 7.410e+02 4.240e+02 3.710e+02
 5.530e+02 7.000e+00 4.910e+02 3.140e+02 5.730e+02 5.980e+02 7.650e+02
 1.370e+02 7.260e+02 6.440e+02 8.060e+02 9.320e+02 3.290e+02 5.630e+02
 7.690e+02 1.066e+03 1.039e+03 1.045e+03 1.013e+03 6.310e+02 7.170e+02
 5.810e+02 8.570e+02 3.520e+02 8.400e+01 4.090e+02 9.540e+02 4.490e+02
 1.600e+02 6.540e+02 1.018e+03 4.180e+02 5.030e+02 1.530e+02 9.380e+02
 7.090e+02 1.650e+02 1.510e+02 6.500e+01 8.000e+00 5.330e+02 9.210e+02
 7.000e+02 7.550e+02 4.790e+02 8.240e+02 8.440e+02 3.510e+02 6.900e+02
 1.032e+03 1.010e+02 3.830e+02 5.200e+01 7.530e+02 5.640e+02 5.940e+02
 1.730e+02 1.012e+03 6.460e+02 8.330e+02 8.950e+02 3.670e+02 4.590e+02
 6.110e+02 4.920e+02 1.740e+02 1.042e+03 4.020e+02 8.650e+02 7.700e+01
 6.200e+02 5.540e+02 8.180e+02 2.390e+02 7.050e+02 1.800e+02 3.490e+02
 7.540e+02 8.410e+02 7.640e+02 6.650e+02 2.970e+02 9.880e+02 1.014e+03
 5.210e+02 6.880e+02 1.075e+03 3.000e+00 2.610e+02 7.670e+02 4.760e+02
 1.081e+03 4.280e+02 3.130e+02 2.710e+02 4.500e+02 1.080e+03 2.140e+02
 2.000e+01 7.800e+02 4.670e+02 1.030e+03 7.750e+02 1.190e+02 1.700e+02
 4.430e+02 6.870e+02 5.710e+02 9.500e+02 2.410e+02 2.580e+02 8.630e+02
 7.150e+02 1.250e+02 9.290e+02 7.040e+02 3.770e+02 4.510e+02 7.070e+02
 8.760e+02 8.200e+01 4.110e+02 3.350e+02 4.270e+02 5.160e+02 1.590e+02
 5.060e+02 4.000e+00 5.930e+02 3.800e+02 9.130e+02 9.720e+02 6.820e+02
 2.960e+02 4.400e+02 8.420e+02 1.890e+02 5.050e+02 6.150e+02 7.280e+02
 4.370e+02 4.140e+02 2.860e+02 6.970e+02 1.610e+02 6.950e+02 8.820e+02
 8.280e+02 1.550e+02 2.340e+02 9.830e+02 1.320e+02 9.730e+02 3.100e+02
 5.410e+02 1.100e+01 2.430e+02 5.170e+02 3.300e+02 7.060e+02 4.530e+02
 3.280e+02 3.630e+02 5.870e+02 5.800e+02 2.020e+02 3.400e+01 2.090e+02
 6.280e+02 6.890e+02 9.790e+02 9.530e+02 1.072e+03 5.890e+02 1.410e+02
 5.970e+02 3.780e+02 4.210e+02 1.820e+02 3.500e+02 8.460e+02 1.500e+02
 7.100e+01 7.990e+02 1.400e+01 7.830e+02 9.200e+02 8.490e+02 9.360e+02
 2.590e+02 6.320e+02 3.330e+02 6.960e+02 1.002e+03 2.490e+02 1.074e+03
 7.450e+02 3.720e+02 1.005e+03 7.910e+02 1.040e+03 5.020e+02 6.000e+02
 6.120e+02 9.510e+02 4.000e+02 1.058e+03 3.890e+02 5.280e+02 3.940e+02
 3.530e+02 6.840e+02 9.250e+02 7.140e+02 6.070e+02 9.390e+02 6.690e+02
 6.270e+02 3.690e+02 3.310e+02 9.660e+02 3.250e+02 9.100e+02 9.980e+02
 3.620e+02 2.190e+02 5.100e+02 2.040e+02 1.090e+02 9.180e+02 4.640e+02
 7.380e+02 3.440e+02 9.590e+02 9.440e+02 2.310e+02 6.340e+02 1.067e+03
 9.040e+02 7.100e+02 3.680e+02 4.730e+02 8.500e+01 8.590e+02 9.060e+02
 1.078e+03 3.000e+02 1.077e+03 7.320e+02 3.120e+02 2.170e+02 7.270e+02
 1.021e+03 1.400e+02 5.660e+02 5.580e+02 7.770e+02 6.760e+02 3.860e+02
 4.630e+02 1.003e+03 8.050e+02 1.060e+02 7.850e+02 3.800e+01 1.200e+01
 3.200e+02 4.360e+02 3.570e+02 5.560e+02 8.840e+02 4.380e+02 5.950e+02
 7.890e+02 3.820e+02 1.830e+02 1.900e+02 1.030e+02 2.210e+02 9.920e+02
 7.870e+02 2.800e+01 2.600e+02 5.790e+02 6.250e+02 7.240e+02 1.140e+02
 5.480e+02 3.990e+02 3.200e+01 9.190e+02 2.670e+02 8.930e+02 6.930e+02
 2.550e+02 4.060e+02 9.470e+02 4.100e+01 8.380e+02 5.150e+02 2.450e+02
 5.770e+02 9.760e+02 5.270e+02 9.500e+01 7.500e+01 8.070e+02 5.960e+02
 8.980e+02 9.970e+02 8.010e+02 7.720e+02 6.750e+02 7.160e+02 4.600e+02
 6.260e+02 7.180e+02 9.630e+02 6.700e+02 1.051e+03 5.550e+02 4.410e+02
 6.050e+02 1.054e+03 6.170e+02 9.820e+02 2.990e+02 3.960e+02 3.750e+02
 2.950e+02 7.080e+02 6.990e+02 8.600e+02 2.280e+02 1.990e+02 4.520e+02
 1.076e+03 6.390e+02 9.640e+02 1.006e+03 3.760e+02 1.840e+02 4.540e+02
 6.770e+02 2.520e+02 8.560e+02 4.960e+02 6.940e+02 2.650e+02 1.033e+03
 5.620e+02 3.840e+02 5.840e+02 6.380e+02 4.570e+02 2.930e+02 4.480e+02
 3.370e+02 8.080e+02 8.360e+02 2.100e+01 3.430e+02 3.400e+02 1.000e+02
 5.440e+02 8.970e+02 2.640e+02 2.000e+02 9.000e+02 3.100e+01 8.100e+02
 1.026e+03 5.750e+02 9.840e+02 9.010e+02 9.110e+02 1.100e+02 9.200e+01
 4.500e+01 1.038e+03 2.400e+01 3.150e+02 7.480e+02 6.080e+02 1.910e+02
 8.600e+01 2.730e+02 8.880e+02 6.290e+02 1.079e+03 7.300e+02 1.000e+00
 9.850e+02 3.420e+02 1.700e+01 1.180e+02 8.100e+01 8.430e+02 4.080e+02
 2.770e+02 2.260e+02 2.220e+02 1.017e+03 7.420e+02 2.900e+01 5.510e+02
 4.470e+02 3.850e+02 1.720e+02 2.380e+02 3.560e+02 1.041e+03 6.430e+02
 1.870e+02 8.200e+02 8.890e+02 1.069e+03 6.100e+01 2.030e+02 3.230e+02
 8.250e+02 8.370e+02 3.660e+02 9.680e+02 1.073e+03 5.780e+02 3.410e+02
 8.510e+02 3.220e+02 3.300e+01 6.550e+02 3.980e+02 7.930e+02 8.150e+02
 9.860e+02 1.170e+02 6.400e+02 7.200e+01 9.350e+02 8.160e+02 1.040e+02].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Evaluation

In [ ]:
# accuracy, recall, precision, auc graph, confusion matrix

def eval_model(pred_list, name_list, y_test):
    for pred, name in zip(pred_list, name_list):
        accuracy = accuracy_score(y_test , pred)
        recall = recall_score(y_test, pred)
        precision = precision_score(y_test, pred)
        auc = roc_auc_score(y_test, pred)
        matrix = confusion_matrix(y_test, pred)

        plt.figure(figsize=(8,3))
        plt.subplot(1, 2, 1)
        fpr, tpr, thresholds = roc_curve(y_val, pred, pos_label=1)
        # roc_auc = auc(fpr, tpr)
        plt.plot(fpr, tpr, color='darkorange')
        plt.plot([0, 1], [0, 1], color = 'black', label = 'y = x')
        plt.subplot(1, 2, 2)
        sns.heatmap(matrix, annot=True, fmt='g') # fmt='g' : 지수 표기를 일반 표기로
        plt.title('{0} Model Confusion Matrix'.format(name))
        plt.show()
        plt.tight_layout()

        print('{0} 정확도: {1:.4f}'.format(name, accuracy))
        print('{0} Recall: {1:.4f}'.format(name, recall))
        print('{0} Precision: {1:.4f}'.format(name, precision))
        print('{0} AUC: {1:.4f}'.format(name, auc))

        print('='* 50)
        print()